### ISSUE TITLE
Question about script/improvements suggested

### ISSUE THREAD

**Issue by JanisPlayer** [gekigek99/minecraft-vanilla-server-hibernation#15]
Is it planned to be able to pause the process?
And can you not let the port listen to that of the server when the server is stopped?
You can simply query the number of players.
Can the motd be transferred or replaced with a text?

**Comment by gekigek99** [comment]
Are these requests or just doubts?
1) what process do you mean?
2) "server" you mean the Minecraft server? If so my program is not listening on the Minecraft server port... It's just establishing a connection to it when a player connects
3) I'm interested in that... If you know more documentation about some sort of minecraft API I would really be interested
4) you can change the Minecraft server motd in server.properties (it won't be visible until the first player connects tho (since the server would be offline))

**Comment by JanisPlayer** [comment]
1.
Will you be able to pause the Minecraft server soon?
Usually the problem is not the RAM, but the tasks that reload the worlds and reload the CPU.
Even if only minimally, this can be disruptive for many servers on a system, even if you unload the worlds etc.
A process pause on some of my servers can be just the thing. Of course, forwarding must be used here.
2.
Okay, yes you can change that, so that the server socket is always closed when the Minecraft server starts and that it opens when the Minecraft server is stopped.
So he jumped in for the Minecraft server and not just forwarding.
Although I think the solution with putting it through is good.
I just have to adjust my restart scripts and services.
3.
I looked for an example of Python and came across it.
https://github.com/Dinnerbone/mcstatus
I am not allowed to send Minecraft Souce Code, otherwise I would have done so.
4.
You could add that to the server socket.
The code is either in Minecraft and needs to be rewritten for Python, but there are examples as far as I've seen.
Then you could also transfer the motd.
So you can show the motd to the players even when the server is offline.


It's a lot of work, but yes, these are just suggestions.
Maybe I'll expand a snippet of code.
Unfortunately write on C ++ and haven't used Python for a long time, otherwise I would have quickly expanded the code myself and sent it to you.

**Comment by gekigek99** [comment]
Hi sorry for the delay... I'm in uni you know...

1) we are working on creating a docker container that can be paused when no player are online
2) I think the scripts does what you mean: it establishes the connection to minecraft server only when the first player connects)
3) ok thanks! I will look at the link
4) I thought of that at I would be pretty cool... I can add it in the projects
