### ISSUE TITLE
The system cannot find the path specified. Windows compatibility issue.

### ISSUE THREAD

**Issue by pixelblob** [gekigek99/minecraft-vanilla-server-hibernation#18]
Im most likely being dumb here but im not used to python and code in general,
was wondering how i specify a path. "C:\Servs\1.16.1" Wont work...

**Comment by pixelblob** [comment]
Im on windows btw...

**Comment by gekigek99** [comment]
@pixelblob did you mange to solve the issue?

**Comment by pixelblob** [comment]
Sadly not, but i think its just because im on windows because the hibernation scripts says i dont have screen.

**Comment by gekigek99** [comment]
yep i guessed it was for that...
so yesterday i updated the readme adding some instructions to make it work on windows

can you try again modifying it a little bit (as specified in the readme) and try again?

**Comment by gekigek99** [comment]
moved to #19
