### ISSUE TITLE
Windows compatibility feature

### ISSUE THREAD

**Issue by gekigek99** [gekigek99/minecraft-vanilla-server-hibernation#19]
make the python version windows compatible.

(it's better to maintain just one file and use different if to execute different instructions)

**Comment by pixelblob** [comment]
I feel like i might have done something wrong i got "Exception in main(): name 'Popen' is not defined"

**Comment by pixelblob** [comment]
I changed Popen to open and now im getting PIPE is not defined

**Comment by pixelblob** [comment]
I forgot to add a bit of code so i added it but now im getting "Exception in main(): 'stdout' is an invalid keyword argument for open()"

**Comment by pixelblob** [comment]
I change p = open to Popen and the server started

**Comment by pixelblob** [comment]
![image](https://user-images.githubusercontent.com/34137159/87805394-8bb6a680-c855-11ea-81b8-aac5bbbf9085.png)
Though this now happens when the server tries to stop itself

**Comment by gekigek99** [comment]
ok we are making progress here!

I modified the instructions on the readme file to solve this problem! Could you try them out and tell me if you encounter any errors?

p.s.
I want to specify that this is just a temporary solution for people like you that need the software running for windows (I'm quite busy with studing in this period) but in 2 weeks I'll release a more robust and updated version.

**Comment by pixelblob** [comment]
Sorry for interrupting your study time, thnx for doing this.
![image](https://user-images.githubusercontent.com/34137159/87839487-5339bb80-c89b-11ea-9ef3-e21aa62917c3.png)

**Comment by pixelblob** [comment]
Sry i left something out, yep this works.

thank you!

**Comment by gekigek99** [comment]
@pixelblob you are welcome!

 If you like the project I would appreciate if you leave a star! ;)

**Comment by pixelblob** [comment]
sure thing

**Comment by gekigek99** [comment]
I added windows compatibility to the python version

(windows compatibility for the go script is coming)

**Comment by gekigek99** [comment]
also the go script has windows compatibility now

**Comment by gekigek99** [comment]
see 250920543a3e6e6c659f4641233b5b96250447de commit
