### ISSUE TITLE
Connection Refused in Minecraft Version 1.16.2

### ISSUE THREAD

**Issue by GavvyDizzle** [gekigek99/minecraft-vanilla-server-hibernation#20]
I've been using the script for months now without any problems. It even worked in versions 1.16.0 and 1.16.1. Once I updated my server to 1.16.x the message telling clients how long it is until the server comes up isn't showing anymore. And with my current problem, I am getting the message "Exception in main(): [Errno 111] Connection refused" once I try to connect after the server has started. Any help is appreciated. Also, do you have any plans on updating the script to 1.16.2 for Linux?

**Comment by gekigek99** [comment]
@GavvyDizzle Hi! did you manage to solve the issue?
can you explain how you did so this thread can be helpful also to others?

what do you mean by "update the script to 1.16.2 for linux"?

**Comment by GavvyDizzle** [comment]
Sorry for making the thread without fully checking all angles of the problem I was having. It was due to an issue with an outdated mod, not a connection issue like google made it out to be. I also used this to bring up the startup message and how it doesn't show in 1.16.2 (you already created a new issue for this). And by update for 1.16.2 Linux, I more or less meant fix the invisible startup message and maybe optimize or fix anything else.

**Comment by gekigek99** [comment]
oh okok i already posted the solution for the missing "starting server time warning"

Yes I would like to update a little both the python and the golang scripts to make them similar (the golang has started drifting on his own path ahahah)

and other problems

**Comment by gekigek99** [comment]
@GavvyDizzle if you like this script could I ask you to leave a star? It would be very apperciated
