### ISSUE TITLE
warning "time remaining to server-up" not showing in 1.16.2 version

### ISSUE THREAD

**Issue by gekigek99** [gekigek99/minecraft-vanilla-server-hibernation#21]
mojang probaby changed some rules and I would like to know how @najtin come up with the string to communicate the warning during server startup.

did you just captured the the bytes exchanged with the clients to reproduce them? if so how did you make the minecraft server send those?

Just to avoid tons of hours to solve this "stupid" issue.
thanks

**Comment by gekigek99** [comment]
ok i think i solved it:

they updated the way they are communicating to the client...

this is the new updated way:
```
message := "hello" 
message = "{\"text\":\"" + message + "\"}"
header1 := string(len(message) + 2)
header2 := string("\x00")
header3 := string(len(message))
message = header1 + header2 + header3 + message
messagebyte := []byte(message)
```

soon I will update both the scripts

**Comment by gekigek99** [comment]
updated the python script

**Comment by najtin** [comment]
> ok i think i solved it:
> 
> they updated the way they are communicating to the client...
> 
> the example I studied is: `\x4A\x00\x48{"translate":"multiplayer.disconnect.outdated_client","with":["1.16.2"]}`
> 
> this is the new updated way:
> 
> ```python
> message := "hello" 
> message = "{\"text\":\"" + message + "\"}"
> message = hex(len(message) + 2) + "\x00"+ hex(len(message)) + message
> message = message.encode()
> ```
> 
> soon I will update both the scripts

This looks really nice. This is probably close to the way it worked in earlier versions, too. What i did is i saw that messages of a certain length work with the prefix and i went with that. Your solutions is much more sophisticated. :+1:

**Comment by gekigek99** [comment]
Yes now that I checked carefully it always worked in that way...

still I don't understand why in the version 1.16.2 it was not working

**Comment by gekigek99** [comment]
see f821dadd8b5f4c899bb991db146f4d9262587ab5 commit
