### ISSUE TITLE
Problems with the newest version

### ISSUE THREAD

**Issue by GavvyDizzle** [gekigek99/minecraft-vanilla-server-hibernation#26]
When trying to run the latest version of the python script I encountered a few errors. Some I was able to fix, others I am not. 

- On line 19 "true" should start with a capital T.
- It may have been a problem created on my end but lines 194-200 were giving improper indentation/spacing errors. I fixed by just readjusting the spacing.

After fixing these issues, the script would start but after starting up the server it would send me the error message:
- "Exception in main(): a bytes-like object is required, not 'NoneType'"
- Also, it wouldn't show the startup message.
- Lastly, when joining the server after it says the server is up it keeps throwing the error "Exception in main(): [Errno 24] Too many open files" and doesn't let me join my server.

**Comment by gekigek99** [comment]
ok i am aware of some of these problems... thanks for reporting
this evening i'll upload a morerobust version

**Comment by gekigek99** [comment]
ok I drafted a new release to fix some bugs...
Now it works perfectly fine for me for both scripts, for both win and linux and for all minecraft server versions.

If you like this script would you like to leave a start? It would be very appreciated

**Comment by GavvyDizzle** [comment]
Everything works as expected. Thanks for fixing it so quickly
