### ISSUE TITLE
problem with setting up minecraft-vanilla-server-hibernation 

### ISSUE THREAD

**Issue by ChapperNi** [gekigek99/minecraft-vanilla-server-hibernation#3]
I need some help setting this up for a Forge server. Thanks.

**Comment by ChapperNi** [comment]
I should add that my minecraft version is 1.12.2

**Comment by gekigek99** [comment]
ok so the good thing about this program is that is completely separated from whatever minecraft version you have.

have you downloaded the last release? if not do so.

(i would advise to put the python file in the server folder so everything is in there.)

1) on server.properties set the server-port to 25555 (be careful: when you access from minecraft client you will have to use port 25565)
2) on your router open port 25565
3) set START_MINECRAFT_SERVER = 'cd [PATH/TO/SERVERFOLDER]; screen -dmS minecraftSERVER nice -19 java -jar [minecraft_server.jar]'
you must specify: [PATH/TO/SERVERFOLDER] and [minecraft_server.jar -->(name of jar executable)]
4) set STOP_MINECRAFT_SERVER = "screen -S minecraftSERVER -X 'stop\\n'"
5) set this python program to launch at reboot

p.s. if you are good at playing with services it works too

**Comment by gekigek99** [comment]
if you like this program share it with your friends and give a star!
thanks

**Comment by ChapperNi** [comment]
hello, what do i run the program with? Command prompt?

**Comment by gekigek99** [comment]
are you running on windows?

if so you can run it with this on the command prompt: 
[1] python minecraft-vanilla-server-hibernation.py
or
[2] python3 minecraft-vanilla-server-hibernation.py

tip: create a .bat file and write "[1] or [2]" --> you will just need to double click the bat file to run it

but i would advise to start the program at reboot

**Comment by ChapperNi** [comment]
Yep, when I try to join it says "screen is not recognized as an internal or external command"

**Comment by ChapperNi** [comment]
Also if I try to run the server with the hibernation script, it says the port is already binded.

**Comment by gekigek99** [comment]
okok i see so for server management the professional way would be to use ubuntu where you can install and use the command "screen" to detach a process from the terminal.

for testing purposes you can just use:
> START_MINECRAFT_SERVER = 'java -jar minecraft_server.jar'
in this way you will see the logging info on the terminal (which is no big deal anyway)

for that there could be multiple causes:
1) you have to wait at least 20 seconds before restarting the hibernation script
2) check that the pc/server port is open (or the firewall is deactivated --> use only for testing purposes!)
3) check that the router port 25565 is open
4) check that no other services are running on port 25565
remember to set 25555 on server.properties and connect with the minecraft client to port 25565
