### ISSUE TITLE
Access server command line? (linux)

### ISSUE THREAD

**Issue by ahlsen95** [gekigek99/minecraft-vanilla-server-hibernation#33]
Is it any way possible to access the server command line? Starting the script @reboot with crontab and launching the server.jar in a screen session as readme explains. Can't find any running screen sessions, but can connect to the server with minecraft client?

**Comment by gekigek99** [comment]
> can connect to the server with minecraft client?

do you have a problem accessing the world from the minecraft client?

if the minecraft server is running, you should be able to enter the screen session via this command `screen -r minecraftServer`

**Comment by gekigek99** [comment]
If you like this script it would be really appreciated if leave a star!
thanks!

**Comment by ahlsen95** [comment]
Not having any problems entering the world. Only problem is that i cant seem to find any screens. with screen -r minecraftServer I get "There is no screen to be resumed matching minecraftServer.", and if I try to list current screens with -ls, "No Sockets found in /run/screen/S-minecraft." is replied.

**Comment by gekigek99** [comment]
From [stackoverflow](https://stackoverflow.com/a/21029594):  
> init scripts are run as root, and screens belong to different users. When you type screen -ls you will see the screens of the current user, not all screens on the system.

Can you try to access the screen as root?

**Comment by ahlsen95** [comment]
I just found out. I had to access the screen with sudo commands, yes.  New to linux, woops.

**Comment by gekigek99** [comment]
Glad you found the solution!
