### ISSUE TITLE
Go and Python: add comments

### ISSUE THREAD

**Issue by gekigek99** [gekigek99/minecraft-vanilla-server-hibernation#36]

**Comment by gekigek99** [comment]
go comments added: 3e66b6e706bf9da9e6d6aef022b1f1c2357825eb

**Comment by gekigek99** [comment]
py comments added: e8636c67913a9f40b1247b2e6f90dc12150cb58e

**Comment by gekigek99** [comment]
ok I added some explanations in the code!

@lubocode tell me if you can understand a bit better now ;)

**Comment by lubocode** [comment]
I didn't try to comprehend the whole script, but it seems well enough commented to do that without problems now.
We can just add comments as the code evolves then and close this issue, I would say.

**Comment by gekigek99** [comment]
ok good...
if on the run you find something that is unclear you can just ask me and i'll specify better in the comments
